### ISSUE TITLE
Empty earth file crashes on some windows machines (mp engine)

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1147] opened 2018-06-27 14:55 UTC
osgearth_viewer crashes on some windows machine with empty earth file:

```
set OSGEARTH_TERRAIN_ENGINE=mp
osgearth_viewer test.earth
```

test.earth
```xml
<map name="test" type="geocentric">
</map> 
```

the crash is undefined in the gpu driver. But this should not happen.

```
DrvPresentBuffers + 0x917184
DrvPresentBuffers + 0x1600706
DrvPresentBuffers + 0x1602251
DrvPresentBuffers + 0x1543486
osg::DrawElementsUShort::draw + 0x342
osg::Drawable::draw + 0x350
osgUtil::RenderLeaf::render + 0x197
osgUtil::RenderBin::drawImplementation + 0x306
osgUtil::RenderBin::draw + 0x110
osgUtil::RenderBin::drawImplementation + 0x435
osgUtil::RenderStage::drawImplementation + 0x466
osgUtil::RenderBin::draw + 0x110
osgUtil::RenderStage::drawInner + 0x228
osgUtil::RenderStage::draw + 0x1310
osgUtil::SceneView::draw + 0x3627
osgViewer::Renderer::draw + 0x848
```

The system has the following configuration:

```
osgEarth Library 2.10.0 DEVELOPMENT 

[osgEarth]  [Registry] Terrain engine set from environment: mp
[osgEarth]  [Capabilities] osgEarth Version: 2.10.0 DEVELOPMENT 
[osgEarth]  [Capabilities] Detected hardware capabilities:
[osgEarth]  [Capabilities]   Vendor = NVIDIA Corporation
[osgEarth]  [Capabilities]   Renderer = Quadro K420/PCIe/SSE2
[osgEarth]  [Capabilities]   Version = 3.3.0 NVIDIA 353.30
[osgEarth]  [Capabilities]   Core Profile = yes
[osgEarth]  [Capabilities]   Max GPU texture units = 32
[osgEarth]  [Capabilities]   Max GPU texture coord indices = 8
[osgEarth]  [Capabilities]   Max GPU attributes = 16
[osgEarth]  [Capabilities]   Max texture size = 16384
[osgEarth]  [Capabilities]   Max lights = 1
[osgEarth]  [Capabilities]   GLSL = yes
[osgEarth]  [Capabilities]   GLSL Version = 330
[osgEarth]  [Capabilities]   Texture arrays = yes
[osgEarth]  [Capabilities]   3D textures = yes
[osgEarth]  [Capabilities]   Multitexturing = yes
[osgEarth]  [Capabilities]   draw instanced = yes
[osgEarth]  [Capabilities]   uniform buffer objects = yes
[osgEarth]  [Capabilities]   NPOT textures = yes
[osgEarth]  [Capabilities]   Texture buffers = yes
[osgEarth]  [Capabilities]   Texture buffer max size = 134217728
[osgEarth]  [Capabilities]   Transform feedback = yes
[osgEarth]  [Capabilities]   Compression = ARB S3 RG
```

**Comment by emminizer** [comment] 2018-06-27 15:13
Hi Remoe, just a heads up that I tried to reproduce in 388.19 driver on an NVS 510/PCIe/SSE2 and it worked without problem.  OSG 3.6.1 had a few issues with VBO crashes that looked a lot like this.  I recommend trying OSG 3.6.2-rc2.

IIRC the exact change that helped my case at least was https://github.com/openscenegraph/OpenSceneGraph/commit/6b38107f451

The problem was that the VBO for vertices didn't match in size with the VBO for colors.  Presumably it could have been any other array attribute parameter.  Anyways, if you didn't decide on `BIND_PER_VERTEX` until after `setNormalArray()` call you got a crash.  See also the somewhat long thread starting at https://www.mail-archive.com/osg-users@lists.openscenegraph.org/msg76699.html

I had done a pass on osgEarth code that had this pattern a couple of months back, but it's possible something was missed or something snuck in since then.

Or, of course, it could be completely unrelated.  But the stack trace looks identical and the behavior sounds the same too.

 - Dan

**Comment by remoe** [comment] 2018-06-27 15:23
Dan, thanks for your hint! 

Yes, we use OSG 3.6.1, but we had this crash also on OSG 3.5.6.

**Comment by remoe** [comment] 2018-06-27 16:13
Windows Update has updated Windows 10 Enterprise to this version: 17134.112. NVidia driver is now on 369.09. And it works. But it should also run without this driver update.

**Comment by remoe** [comment] 2018-06-27 16:33
I've tested now with OSG 3.6.2RC2 with NVidia Driver 353.30. It crash also :/

**Comment by remoe** [comment] 2018-06-28 07:55
@emminizer, do you have tested with 'mp' engine? It crash only with 'mp' engine. Rex engine works.

**Comment by emminizer** [comment] 2018-06-28 09:37
No.  I only just now tested with mp; most of our testing is Rex based.  MP does not draw anything and reports OpenGL errors.  One of the first of them points to a bad call with glVertexAttribPointer().  We used to see similar issues on Rex a few months back, but that was fixed by, I think, https://github.com/gwaldron/osgearth/commit/b0bc502eba

**Closed** 2018-07-02 16:42 UTC
