### ISSUE TITLE
Tethering: How to level out the camera after breaking a tether

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#2381] opened 2023-11-15 14:19 UTC
### Discussed in https://github.com/gwaldron/osgearth/discussions/2380

<div type='discussions-op-text'>

<sup>Originally posted by **elbarto1980** November 15, 2023</sup>
Hi,
I have a question about how to restore the correct behavior of the EarthManipulator after having tethered it to a node, using the TETHER_CENTER_AND_ROTATION mode.
When I break the tether using the clearViewpoint() method, the camera is left in a weird state and it is not controllable. To restore its correct behavior, I have to change the tether mode to TETHER_CENTER, wait for the camera to be "realigned" and only then I can break the tether.

I saw in the the EarthManipulator.cpp file that it does that [here](https://github.com/gwaldron/osgearth/blob/2b61f0e530e0bab78ec4d631c08b0cbd5bc1ec46/src/osgEarth/EarthManipulator.cpp#L2004C20-L2004C20), but I can't figure out how to do that in my code, outside the EarthManipulator class.

You can reproduce the issue using the osgeart_manip demo application if you break the tether when the TETHER_CENTER_AND_ROTATION mode is active.

What is the best way to restore the manipulator when this happens?

Thank you for your help!

P.S.: These are my caps...
```
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set
[osgEarth]  [Capabilities] Capabilities: 
[osgEarth]  [Capabilities]   osgEarth Version:  3.2.0 build 113
[osgEarth]  [Capabilities]   OSG Version:       3.6.5
[osgEarth]  [Capabilities]   GDAL Version:      3.0.4
[osgEarth]  [Capabilities]   GEOS Version:      3.8.0
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 4.6.0 NVIDIA 535.129.03
[osgEarth]  [Capabilities]   GL Core Profile:   no
```

</div>

**Comment by gwaldron** [comment] 2023-11-16 13:51
Note: This should be a simple matter of applying the "tether break realignment" code as necessary when setViewpoint happens

**Comment by gwaldron** [comment] 2023-11-20 13:29
Pushed a patch for this to 79172142e, please test and report back.

**Comment by elbarto1980** [comment] 2023-11-21 12:22
Hi, I am sorry but cannot test it right away because, unfortunately, the latest release that gets along with my code is the osgearth-3.2.
Now, I am trying to fix all the build errors... I will let you know asap. Thank you!

**Comment by elbarto1980** [comment] 2023-11-22 09:11
By commenting out here and there, I was finally able to build my code and I can confirm that the patch works flawlessly. Thanks! :+1: 

I have a few side effects now (not caused by the patch, of course) because my linux application wasn't ready to move from GL2 to GL3 yet. For example, GL3 gave my models a new fresh coat of radioactive green paint... but I will figure it out eventually (any suggestions are very welcome 😄)
![GL_Comparison](https://github.com/gwaldron/osgearth/assets/36400622/c8d16751-41b1-45cb-afc6-8500e2c61c3a)

**Comment by gwaldron** [comment] 2023-11-22 12:56
Try running the shader generator on your model.
```c++
osgEarth::ShaderGenerator gen;
gen.run(node);
```

**Comment by elbarto1980** [comment] 2023-11-22 13:41
I did, those lines where already there from a previous attempt to upgrade osgearth. Here's how I load a model:

```
void DifferentialUGV::loadModel() {
    QDir localPath(QCoreApplication::applicationDirPath());
    localPath.cd("../res");
    auto resPath = localPath.absolutePath().toStdString();

    osg::ref_ptr<osg::Node> body = osgDB::readRefNodeFile(resPath + "/OsgModels/CombatVehicle/CombatVehicle.osgt.osgearth_shadergen");

    ugvGroup = new osg::Group();
    ugvGroup->setName("Differential UGV Group");
    ugvGroup->addChild(body);

    osgUtil::Optimizer opt;
    opt.optimize(ugvGroup, osgUtil::Optimizer::INDEX_MESH);
    osgEarth::ShaderGenerator gen;
    gen.run(ugvGroup);

    if (pat.valid()) {
        pat->addChild(ugvGroup);
    }

    if (root.valid()) {
        optimizer.optimize(root);
    }
}
``` 

I noticed that at a specific yaw angle, the model becomes white, and then it turns green again.

I have the same behavior if I load the cessna model from OpenSceneGraph-Data. On the contrary the cow.osgt file is rendered correctly, but it keeps printing the following warning messages:

```
Warning: detected OpenGL error 'invalid enumerant' at after RenderBin::draw(..)
Warning: TexGen::apply(State&) - not supported.
Warning: TexGen::apply(State&) - not supported.
```

Thank you!
(I do not want to go out of topic here... we can move to another discussion if you want)

**Comment by elbarto1980** [comment] 2023-11-22 19:33
I did, those lines were already there from a previous attempt to upgrade osgearth. Here's how I load a model:

```
void DifferentialUGV::loadModel() {
    QDir localPath(QCoreApplication::applicationDirPath());
    localPath.cd("../res");
    auto resPath = localPath.absolutePath().toStdString();

    osg::ref_ptr<osg::Node> body = osgDB::readRefNodeFile(resPath + "/OsgModels/CombatVehicle/CombatVehicle.osgt.osgearth_shadergen");

    ugvGroup = new osg::Group();
    ugvGroup->setName("Differential UGV Group");
    ugvGroup->addChild(body);

    osgUtil::Optimizer opt;
    opt.optimize(ugvGroup, osgUtil::Optimizer::INDEX_MESH);
    osgEarth::ShaderGenerator gen;
    gen.run(ugvGroup);

    if (pat.valid()) {
        pat->addChild(ugvGroup);
    }

    if (root.valid()) {
        optimizer.optimize(root);
    }
}
``` 

I noticed that, at a specific yaw angle, the model becomes white and then it turns green again.

I have the same behavior if I load the cessna model from OpenSceneGraph-Data. On the contrary the cow.osgt file is rendered correctly, but it keeps printing the following warning messages:

```
Warning: detected OpenGL error 'invalid enumerant' at after RenderBin::draw(..)
Warning: TexGen::apply(State&) - not supported.
Warning: TexGen::apply(State&) - not supported.
```

Thank you!
(I do not want to go off topic here... we can move to another discussion if you want)

**Comment by elbarto1980** [comment] 2023-11-23 13:20
Hi, I have a relevant **update**. I hope it might be helpful, too.
I found out that when I add a model, colors are mixed up... but in a _deterministic_ way.
Please, look at the following image:
![Textured](https://github.com/gwaldron/osgearth/assets/36400622/5e1881f5-825a-4a8d-a0a9-d135bcba3e23)

Here is what happens:
1. In the first (upper-left) image, the model has its own texture, but it has a red overlay that it takes from the color of the label (I think you might have to zoom in);
2. Then I press the keyboard button 's' that shows statistics. As the "Frame Rate" text appears, the model's overlay color becomes white (upper-right image);
3. I press 's' again (lower-left image), and the overlay color turns to orange, as the GPU text in the statistics box;
4. I press 's' twice again (lower-right image) and the overlay is white, as the text in the "View" box.

In the terminal, it prints the message `Warning: detected OpenGL error 'invalid enumerant' at after RenderBin::draw(..)`.

Something similar happens when I load a model that has materials, but no texture.
![Untextured](https://github.com/gwaldron/osgearth/assets/36400622/ecd5ab62-8a94-4ca2-ba52-7220de133e26)

This time, the model's colors/materials are not shown at all. It takes the color of the green label at first, and then the one of the statistics text. No warning messages are printed.

Does this tell anything to you? I hope it could help address the problem I am having...
Thank you!

**Comment by elbarto1980** [comment] 2023-11-28 10:24
@gwaldron, I moved the last comments [here](https://github.com/gwaldron/osgearth/discussions/2389#discussion-5899943), so you could close this issue. Thank you again for your support!

**Comment by elbarto1980** [comment] 2023-11-28 10:33
@gwaldron, I moved the last comment to Support Q&A #2389, so you could close this issue. Thank you again for your support!

**Closed** 2023-12-04 20:42 UTC
Labels: defect
