### ISSUE TITLE
How to use VerticalScale?

### ISSUE THREAD

**Issue by yuhubuxi** [gwaldron/osgearth#1581] opened 2020-09-23 02:05 UTC
Dear gwaldron：
I am a student developer of osgearth, thank you very much for your contribution to the estimated project.
Recently, I encountered some problems when using osgerath to dynamically adjust the VerticalScale. I looked up a lot of material and still couldn't solve it. I hope you can give me some guidance and suggestions about the following two questions.
The first problem is about dynamically adjusting the terrain. I use the VerticalScale function to dynamically adjust the terrain, the code as shown in the following. From the perspective of visual effects, we can see that the shape of the earth change. However, when I zoom in and get close to the ground, the lens will pass through the ground, as shown in Figure 1. There will be a lot of line objects outside of the earth when I shrink and move away from the ground, as shown in Figure 2. In addition, the height I obtain using osgUtil::LineSegmentIntersector::Intersections is the same as before using the VerticalScale function.
 
![image](https://user-images.githubusercontent.com/28517837/93956154-0e8f3c80-fd84-11ea-82fe-8e338922ff01.png)

 
![image](https://user-images.githubusercontent.com/28517837/93956186-223aa300-fd84-11ea-9fd0-d9e1c7753cf2.png)

Figure 1 The phenomenon when zoom in and get close to the ground.
 
![image](https://user-images.githubusercontent.com/28517837/93956206-2f579200-fd84-11ea-8628-4198ba5eab28.png)

Figure 2 The phenomenon when narrow and move away from the ground.

The second problem is, there is no effect when I use addElevationLayer function, the code as shown in the following. Could you tell me what I did wrong?
 
![image](https://user-images.githubusercontent.com/28517837/93956234-41d1cb80-fd84-11ea-8d12-a9ccacee7e4c.png)

Looking forward to your reply.

Best regards

**Comment by yuhubuxi** [comment] 2020-09-23 02:07
I encountered the same problem and have not found a good solution.

**Comment by l1uw3n** [comment] 2020-09-23 02:07
I encountered the same problem and have not found a good solution.

**Comment by l1uw3n** [comment] 2020-09-23 07:13
In addition, when I used osgEarthUtil/VerticalScale to modify the vertical, I pressed "w" and found that the vertices of many graphics seem to be connected to the center of the earth. Is this an error?
![image](https://user-images.githubusercontent.com/24247258/93978979-54adc580-fdaf-11ea-86cc-f20f160b2b36.png)

**Comment by gwaldron** [comment] 2020-09-23 13:23
The problem is that VerticalScale is an old unmaintained class, and it not really compatible with the shader-based terrain engine. OSG's culling doesn't know how to cull terrain vertices that are manipulated in the shader, so you get incorrect culling when your camera gets close to the terrain. There is no solution to this at the moment.

**Comment by yuhubuxi** [comment] 2020-09-24 00:51
Dear gwaldron：
 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I am grateful for your answer. I have tried some methods to solve this problem for a month. Your answer makes me know that is imposiible and saves me time. Therefore, thank you very much.
 
&nbsp;
 
Best regards,
 
Wen Liu.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gwaldron/osgearth"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 晚上9:23
收件人:&nbsp;"gwaldron/osgearth"<osgearth@noreply.github.com&gt;;
抄送:&nbsp;"中国海洋大学-计算机系-马颖"<895896656@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gwaldron/osgearth] How to use VerticalScale? (#1581)





 
The problem is that VerticalScale is an old unmaintained class, and it not really compatible with the shader-based terrain engine. OSG's culling doesn't know how to cull terrain vertices that are manipulated in the shader, so you get incorrect culling when your camera gets close to the terrain. There is no solution to this at the moment.

**Comment by yuhubuxi** [comment] 2020-09-24 12:20
Dear gwaldron：

I am grateful for your answer. I have tried some methods to solve this problem for a month. Your answer makes me know that is imposiible and saves me time. Therefore, thank you very much.



Best regards,

**Comment by gwaldron** [comment] 2020-12-02 22:25
Closing this since vertical scale is not a supported function in 3.x. If someone wants to do a new implementation they are welcome :)

**Closed by gwaldron** 2020-12-02 22:25 UTC
Labels: defect

**Comment by oOoBinoOo** [comment] 2022-09-21 08:42
Hello, have you solved this problem?

**Comment by horrzs** [comment] 2024-03-13 08:38
have solved this problem??? need it very much!
