### ISSUE TITLE
Bad tesselation on concave polygons (2.10)

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#1540] opened 2020-06-25 15:17 UTC
Tesselation does not work as expected for this example (concave polygons with a point on south pole):

```
<model  driver="feature_geom">
                <features name="bboxLine" driver="ogr">
                    <geometry>
MULTIPOLYGON(((163 -90, 229 -89.445633, 229 -88.867989, 229 -88.290342, 229 -87.712689, 229 -87.135031, 229 -86.557365, 229 -85.979689, 229 -85.402002, 229 -84.824303, 229 -84.246589, 229 -83.66886, 229 -83.091114, 229 -82.513348, 229 -81.935563, 229 -81.357755, 229 -80.779924, 229 -80.202068, 229 -79.624186, 229 -79.046276, 229 -78.468336, 229 -77.890366, 229 -77.312363, 229 -76.734327, 229 -76.156255, 229 -75.578146, 229 -75, 229 -60, 229 -30, 224.66667 -30, 220.33333 -30, 216 -30, 211.66667 -30, 207.33333 -30, 203 -30, 203 -5, 199.48194 -5, 195.96389 -5, 192.44583 -5, 188.92778 -5, 187.99963 -7.232482, 187.06167 -9.464444, 185.71889 -12.486944, 185.28194 -13.455556, 184.47278 -15.225, 184.3275 -15.539722, 184.17194 -15.9, 183.18889 -18.148889, 183.01944 -18.530278, 181.53056 -21.8, 180 -25, 177.33333 -25, 174.375 -25, 171.41667 -25, 169.73112 -26.50975, 168 -28, 165.52489 -29.022863, 163 -30, 163 -45, 163 -90)))
                    </geometry>
                </features>
                <geo_interpolation>great_circle</geo_interpolation>
                <styles>
                    <style type="text/css">
                        default {
                            altitude-clamping: terrain;
                            altitude-technique: drape;
							fill: #ffff00ff;
                            stroke: #ff0000;
                            stroke-width: 10px;
                            stroke-smooth: true;
                            stroke-tessellation_size: 100km;
                        }
                    </style>
                </styles>
            </model>
```

![image](https://user-images.githubusercontent.com/17981960/85747580-b22a6b80-b707-11ea-8325-a35c74218185.png)

**Comment by JD31** [comment] 2020-06-25 15:19
[test.zip](https://github.com/gwaldron/osgearth/files/4832241/test.zip)

**Comment by gwaldron** [comment] 2020-06-25 15:20
Possible dupe of #1531

**Comment by JD31** [comment] 2020-06-25 15:25
After reflexion... I think it is more linked to the fact that the polygon crosses the anti meridian.
(I have lot of polygons joining the south pole, and all of them expect this one pass).

**Comment by gwaldron** [comment] 2020-06-25 15:46
Works in 3.0

![image](https://user-images.githubusercontent.com/326618/85752574-85f7f600-b6d9-11ea-97a9-2743d492ee2c.png)

**Comment by JD31** [comment] 2020-06-25 15:51
OK. I am with 2.10.2. I will try to track where the corrections can be...
Thank you.

**Comment by JD31** [comment] 2020-06-25 16:03
The update of Tesselator and Tesselator.cpp with the 3.0 ones correct the defect.
Cool !

**Closed** 2020-06-26 15:16 UTC
Labels: nuisance
