### ISSUE TITLE
clustering by classes 

### ISSUE THREAD

**Issue by jaigsingla** [gwaldron/osgearth#2238] opened 2023-03-15 06:50 UTC
Hi All,

Want to visualize the data in clusters by arranging it in different classes. 

For example , based on country population , circle size and color shall be visualized .. 

or based on population , vertical line strokes shall be identified .

thanks,
Jai

**Comment by gwaldron** [comment] 2023-03-15 12:18
duplicate of #2240

**Closed by gwaldron** 2023-03-15 12:18 UTC
Labels: support
